// 과학적 상식 게시판 데이터
const scienceData = [
  {
    id: 24,
    title: '임신 중 타이레놀 복용과 자폐증 위험 - 과학적 진실은?',
    link: 'science/science-detail-24.html',
    category: '일반상식',
    author: '이호기',
    date: '09-23',
    views: 0,
    summary: '임신 중 타이레놀 복용과 자폐증 위험 - 과학적 진실은?',
  },
  {
    id: 23,
    title: '블록체인',
    link: 'science/science-detail-23.html',
    category: '일반상식',
    author: '이호기',
    date: '09-19',
    views: 0,
    summary: '블록체인의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 22,
    title: '인공지능(AI)과 머신러닝(Machine Learning)의 차이점',
    link: 'science/science-detail-22.html',
    category: '일반상식',
    author: '이호기',
    date: '09-17',
    views: 0,
    summary: '인공지능(AI)과 머신러닝(Machine Learning)의 차이점에 대한 설명',
  },
  {
    id: 21,
    title: '자동차 엔진 오일 교체 주기는 어떻게 정할까?',
    link: 'science/science-detail-21.html',
    category: '일반상식',
    author: '이호기',
    date: '09-15',
    views: 0,
    summary: '자동차 엔진 오일 교체 주기 결정 방법과 관리 요령에 대한 설명',
  },
  {
    id: 20,
    title: '바로크미술',
    link: 'science/science-detail-20.html',
    category: '일반상식',
    author: '이호기',
    date: '09-11',
    views: 0,
    summary: '바로크미술의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 19,
    title: '지구온난화와 온실효과',
    link: 'science/science-detail-19.html',
    category: '일반상식',
    author: '이호기',
    date: '09-09',
    views: 0,
    summary: '지구온난화와 온실효과의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 18,
    title: '대륙붕 (Continental Shelf)',
    link: 'science/science-detail-18.html',
    category: '일반상식',
    author: '이호기',
    date: '09-07',
    views: 0,
    summary: '대륙붕 (Continental Shelf)의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 17,
    title: '가이야 이론 (Gaia theory)',
    link: 'science/science-detail-17.html',
    category: '일반상식',
    author: '이호기',
    date: '09-05',
    views: 0,
    summary: '가이야 이론 (Gaia theory)의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 16,
    title: '플라즈마(Plasma)',
    link: 'science/science-detail-16.html',
    category: '일반상식',
    author: '이호기',
    date: '09-03',
    views: 0,
    summary: '플라즈마의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 15,
    title: '밀도(Density)',
    link: 'science/science-detail-15.html',
    category: '일반상식',
    author: '이호기',
    date: '08-28',
    views: 0,
    summary: '밀도의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 14,
    title: '방사성 원소',
    link: 'science/science-detail-14.html',
    category: '일반상식',
    author: '이호기',
    date: '08-287',
    views: 0,
    summary: '방사성 원소의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 13,
    title: '가르시아 효과(Garcia effect)',
    link: 'science/science-detail-13.html',
    category: '일반상식',
    author: '이호기',
    date: '08-26',
    views: 0,
    summary: '가르시아 효과의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 12,
    title: '바이오시밀러(Biosimilar)',
    link: 'science/science-detail-12.html',
    category: '일반상식',
    author: '이호기',
    date: '08-25',
    views: 0,
    summary: '바이오시밀러의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 11,
    title: '멘델의 법칙',
    link: 'science/science-detail-11.html',
    category: '일반상식',
    author: '이호기',
    date: '08-23',
    views: 0,
    summary: '멘델의 법칙의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 10,
    title: '반성유전',
    link: 'science/science-detail-10.html',
    category: '일반상식',
    author: '이호기',
    date: '08-22',
    views: 0,
    summary: '반성유전의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 9,
    title: '디버깅과 디버거',
    link: 'science/science-detail-9.html',
    category: '일반상식',
    author: '이호기',
    date: '08-21',
    views: 0,
    summary: '디버깅과 디버거',
  },
  {
    id: 8,
    title: '힘의 3요소',
    link: 'science/science-detail-8.html',
    category: '일반상식',
    author: '이호기',
    date: '08-20',
    views: 0,
    summary: '힘의 3요소의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 7,
    title: '쿼크 (Quark)',
    link: 'science/science-detail-7.html',
    category: '일반상식',
    author: '이호기',
    date: '08-19',
    views: 0,
    summary: '쿼크 (Quark)의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 6,
    title: '옴의 법칙',
    link: 'science/science-detail-6.html',
    category: '일반상식',
    author: '이호기',
    date: '08-18',
    views: 0,
    summary: '옴의 법칙의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 5,
    title: '열의 이동',
    link: 'science/science-detail-5.html',
    category: '일반상식',
    author: '이호기',
    date: '08-02',
    views: 0,
    summary: '열의 이동의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 4,
    title: '빛은 여러 가지 현상',
    link: 'science/science-detail-4.html',
    category: '일반상식',
    author: '이호기',
    date: '08-15',
    views: 0,
    summary: '빛은 여러 가지 현상의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 3,
    title: '상대성 이론',
    link: 'science/science-detail-3.html',
    category: '음펨바 효과 (Mpemba Effect)',
    author: '이호기',
    date: '08-14',
    views: 0,
    summary: '음펨바 효과 (Mpemba Effect)의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 2,
    title: "도플러 효과 (Doppler's effect)",
    link: 'science/science-detail-2.html',
    category: '일반상식',
    author: '이호기',
    date: '08-13',
    views: 0,
    summary:
      "도플러 효과 (Doppler's effect)의 개념, 특징, 비교 분석에 대한 설명",
  },
  {
    id: 1,
    title: '아르키메데스의 원리, 부력의 원리',
    link: 'science/science-detail-1.html',
    category: '일반상식',
    author: '이호기',
    date: '08-12',
    views: 0,
    summary:
      '아르키메데스의 원리, 부력의 원리의 개념, 특징, 비교 분석에 대한 설명',
  },
  // 여기에 추가 과학적 상식 데이터를 입력하세요
];
