// 과학적 상식 게시판 데이터
const scienceData = [
  {
    id: 61,
    title: "히크의 법칙(Hick's Law)",
    link: 'science/science-detail-61.html',
    category: '일반상식',
    author: '이호기',
    date: '01-26',
    views: 0,
  },
  {
    id: 60,
    title: '잠금효과(Lock-in Effect)',
    link: 'science/science-detail-60.html',
    category: '일반상식',
    author: '이호기',
    date: '01-21',
    views: 0,
  },
  {
    id: 59,
    title: '스티그마 효과(Stigma Effect)',
    link: 'science/science-detail-59.html',
    category: '일반상식',
    author: '이호기',
    date: '01-16',
    views: 0,
  },
  {
    id: 58,
    title: "맨더빌의 역설(Mandeville's Paradox)",
    link: 'science/science-detail-58.html',
    category: '일반상식',
    author: '이호기',
    date: '01-09',
    views: 0,
  },
  {
    id: 57,
    title: '플린 효과(Flynn Effect)',
    link: 'science/science-detail-57.html',
    category: '일반상식',
    author: '이호기',
    date: '01-05',
    views: 0,
  },
  {
    id: 56,
    title: '레드 셔츠 효과(Red-Shirt Effect)',
    link: 'science/science-detail-56.html',
    category: '일반상식',
    author: '이호기',
    date: '12-30',
    views: 0,
  },
  {
    id: 55,
    title: '시그니처 모멘트(Signature Moment)',
    link: 'science/science-detail-55.html',
    category: '일반상식',
    author: '이호기',
    date: '12-24',
    views: 0,
  },
  {
    id: 54,
    title: '밴드왜건 효과(Bandwagon Effect)',
    link: 'science/science-detail-54.html',
    category: '일반상식',
    author: '이호기',
    date: '12-18',
    views: 0,
  },
  {
    id: 53,
    title: "파킨슨의 법칙(Parkinson's Law)",
    link: 'science/science-detail-53.html',
    category: '일반상식',
    author: '이호기',
    date: '12-16',
    views: 0,
  },
  {
    id: 52,
    title: '핑거 스패닝(Finger Spanning) 효과',
    link: 'science/science-detail-52.html',
    category: '일반상식',
    author: '이호기',
    date: '12-12',
    views: 0,
  },
  {
    id: 51,
    title: '제노비스 증후군(Bystander Effect)',
    link: 'science/science-detail-51.html',
    category: '일반상식',
    author: '이호기',
    date: '12-10',
    views: 0,
  },
  {
    id: 50,
    title: '확증편향(Confirmation Bias)',
    link: 'science/science-detail-50.html',
    category: '일반상식',
    author: '이호기',
    date: '12-08',
    views: 0,
  },
  {
    id: 49,
    title: '선택적 노출(Selective Exposure)',
    link: 'science/science-detail-49.html',
    category: '일반상식',
    author: '이호기',
    date: '12-04',
    views: 0,
  },
  {
    id: 48,
    title: '인지 부조화(Cognitive Dissonance)',
    link: 'science/science-detail-48.html',
    category: '일반상식',
    author: '이호기',
    date: '12-02',
    views: 0,
  },
  {
    id: 47,
    title: '잠재지(Tacit Knowledge) vs 형식지(Explicit Knowledge)',
    link: 'science/science-detail-47.html',
    category: '일반상식',
    author: '이호기',
    date: '11-28',
    views: 0,
  },
  {
    id: 46,
    title: '리바운드 효과',
    link: 'science/science-detail-46.html',
    category: '일반상식',
    author: '이호기',
    date: '11-26',
    views: 0,
  },
  {
    id: 45,
    title: '파레토 최적',
    link: 'science/science-detail-45.html',
    category: '일반상식',
    author: '이호기',
    date: '11-24',
    views: 0,
  },
  {
    id: 44,
    title: '브레튼우즈',
    link: 'science/science-detail-44.html',
    category: '일반상식',
    author: '이호기',
    date: '11-20',
    views: 0,
  },
  {
    id: 43,
    title: '다원적무지',
    link: 'science/science-detail-43.html',
    category: '일반상식',
    author: '이호기',
    date: '11-18',
    views: 0,
  },
  {
    id: 42,
    title: '파량새 증후군',
    link: 'science/science-detail-42.html',
    category: '일반상식',
    author: '이호기',
    date: '11-14',
    views: 0,
  },
  {
    id: 41,
    title: '스낵컬처',
    link: 'science/science-detail-41.html',
    category: '일반상식',
    author: '이호기',
    date: '11-13',
    views: 0,
  },
  {
    id: 40,
    title: '코쿠닝 현상',
    link: 'science/science-detail-40.html',
    category: '일반상식',
    author: '이호기',
    date: '11-11',
    views: 0,
    summary: '코쿠닝 현상',
  },
  {
    id: 39,
    title: 'J턴(J-Turn) 현상, 지방으로 돌아가는 세대의 선택',
    link: 'science/science-detail-39.html',
    category: '일반상식',
    author: '이호기',
    date: '11-06',
    views: 0,
    summary: 'J턴(J-Turn) 현상, 지방으로 돌아가는 세대의 선택',
  },
  {
    id: 38,
    title: '코쿠닝(Cocooning) 현상, 집 안에서 세상을 만나는 시대',
    link: 'science/science-detail-38.html',
    category: '일반상식',
    author: '이호기',
    date: '11-04',
    views: 0,
    summary: '코쿠닝(Cocooning) 현상, 집 안에서 세상을 만나는 시대',
  },
  {
    id: 37,
    title: '바나나현상, 아무것도 짓지 말자는 시대의 역설',
    link: 'science/science-detail-37.html',
    category: '일반상식',
    author: '이호기',
    date: '10-31',
    views: 0,
    summary: '바나나현상, 아무것도 짓지 말자는 시대의 역설',
  },
  {
    id: 36,
    title: '루키즘, 외모가 능력이 되는 사회의 그림자',
    link: 'science/science-detail-36.html',
    category: '일반상식',
    author: '이호기',
    date: '10-29',
    views: 0,
    summary: '루키즘, 외모가 능력이 되는 사회의 그림자',
  },
  {
    id: 35,
    title: '핌피 현상, 이익이 된다면 환영한다는 사회적 역설',
    link: 'science/science-detail-35.html',
    category: '일반상식',
    author: '이호기',
    date: '10-27',
    views: 0,
    summary: '핌피 현상, 이익이 된다면 환영한다는 사회적 역설',
  },
  {
    id: 34,
    title: '노비즘, ‘나는 일하기 싫다’ 시대의 새로운 코드',
    link: 'science/science-detail-34.html',
    category: '일반상식',
    author: '이호기',
    date: '10-23',
    views: 0,
    summary: '노비즘, ‘나는 일하기 싫다’ 시대의 새로운 코드',
  },
  {
    id: 33,
    title: '낙관계수, 불확실성 속 의사결정의 수리적 판단',
    link: 'science/science-detail-33.html',
    category: '일반상식',
    author: '이호기',
    date: '10-21',
    views: 0,
    summary: '낙관계수, 불확실성 속 의사결정의 수리적 판단',
  },
  {
    id: 32,
    title: '공소증후군, 열정이 멈춘 자리에서 오는 허무',
    link: 'science/science-detail-32.html',
    category: '일반상식',
    author: '이호기',
    date: '10-17',
    views: 0,
    summary: '공소증후군, 열정이 멈춘 자리에서 오는 허무',
  },
  {
    id: 31,
    title: '스프롤 현상',
    link: 'science/science-detail-31.html',
    category: '일반상식',
    author: '이호기',
    date: '10-15',
    views: 0,
    summary: '스프롤 현상의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 30,
    title: '블랙컨슈머 vs 스마트 플레이어',
    link: 'science/science-detail-30.html',
    category: '일반상식',
    author: '이호기',
    date: '10-13',
    views: 0,
    summary:
      '블랙컨슈머 vs 스마트 플레이어의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 29,
    title: '그릿(Grit)',
    link: 'science/science-detail-29.html',
    category: '일반상식',
    author: '이호기',
    date: '10-09',
    views: 0,
    summary: '그릿(Grit)의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 28,
    title: '헤일로 효과(Halo Effect)',
    link: 'science/science-detail-28.html',
    category: '일반상식',
    author: '이호기',
    date: '10-03',
    views: 0,
    summary:
      '헤일로 효과의 개념, 특징, 일상생활에서의 적용과 극복 방법에 대한 설명',
  },
  {
    id: 27,
    title: '스프롤 현상',
    link: 'science/science-detail-27.html',
    category: '일반상식',
    author: '이호기',
    date: '10-01',
    views: 0,
    summary: '스프롤 현상의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 26,
    title: '매슬로의 동기이론',
    link: 'science/science-detail-26.html',
    category: '일반상식',
    author: '이호기',
    date: '09-29',
    views: 0,
    summary: '매슬로의 동기이론의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 25,
    title: '텔넷(telnet)',
    link: 'science/science-detail-25.html',
    category: '일반상식',
    author: '이호기',
    date: '09-25',
    views: 0,
    summary: '텔넷(telnet)의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 24,
    title: '임신 중 타이레놀 복용과 자폐증 위험 - 과학적 진실은?',
    link: 'science/science-detail-24.html',
    category: '일반상식',
    author: '이호기',
    date: '09-23',
    views: 0,
    summary: '임신 중 타이레놀 복용과 자폐증 위험 - 과학적 진실은?',
  },
  {
    id: 23,
    title: '블록체인',
    link: 'science/science-detail-23.html',
    category: '일반상식',
    author: '이호기',
    date: '09-19',
    views: 0,
    summary: '블록체인의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 22,
    title: '인공지능(AI)과 머신러닝(Machine Learning)의 차이점',
    link: 'science/science-detail-22.html',
    category: '일반상식',
    author: '이호기',
    date: '09-17',
    views: 0,
    summary: '인공지능(AI)과 머신러닝(Machine Learning)의 차이점에 대한 설명',
  },
  {
    id: 21,
    title: '자동차 엔진 오일 교체 주기는 어떻게 정할까?',
    link: 'science/science-detail-21.html',
    category: '일반상식',
    author: '이호기',
    date: '09-15',
    views: 0,
    summary: '자동차 엔진 오일 교체 주기 결정 방법과 관리 요령에 대한 설명',
  },
  {
    id: 20,
    title: '바로크미술',
    link: 'science/science-detail-20.html',
    category: '일반상식',
    author: '이호기',
    date: '09-11',
    views: 0,
    summary: '바로크미술의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 19,
    title: '지구온난화와 온실효과',
    link: 'science/science-detail-19.html',
    category: '일반상식',
    author: '이호기',
    date: '09-09',
    views: 0,
    summary: '지구온난화와 온실효과의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 18,
    title: '대륙붕 (Continental Shelf)',
    link: 'science/science-detail-18.html',
    category: '일반상식',
    author: '이호기',
    date: '09-07',
    views: 0,
    summary: '대륙붕 (Continental Shelf)의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 17,
    title: '가이야 이론 (Gaia theory)',
    link: 'science/science-detail-17.html',
    category: '일반상식',
    author: '이호기',
    date: '09-05',
    views: 0,
    summary: '가이야 이론 (Gaia theory)의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 16,
    title: '플라즈마(Plasma)',
    link: 'science/science-detail-16.html',
    category: '일반상식',
    author: '이호기',
    date: '09-03',
    views: 0,
    summary: '플라즈마의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 15,
    title: '밀도(Density)',
    link: 'science/science-detail-15.html',
    category: '일반상식',
    author: '이호기',
    date: '08-28',
    views: 0,
    summary: '밀도의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 14,
    title: '방사성 원소',
    link: 'science/science-detail-14.html',
    category: '일반상식',
    author: '이호기',
    date: '08-287',
    views: 0,
    summary: '방사성 원소의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 13,
    title: '가르시아 효과(Garcia effect)',
    link: 'science/science-detail-13.html',
    category: '일반상식',
    author: '이호기',
    date: '08-26',
    views: 0,
    summary: '가르시아 효과의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 12,
    title: '바이오시밀러(Biosimilar)',
    link: 'science/science-detail-12.html',
    category: '일반상식',
    author: '이호기',
    date: '08-25',
    views: 0,
    summary: '바이오시밀러의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 11,
    title: '멘델의 법칙',
    link: 'science/science-detail-11.html',
    category: '일반상식',
    author: '이호기',
    date: '08-23',
    views: 0,
    summary: '멘델의 법칙의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 10,
    title: '반성유전',
    link: 'science/science-detail-10.html',
    category: '일반상식',
    author: '이호기',
    date: '08-22',
    views: 0,
    summary: '반성유전의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 9,
    title: '디버깅과 디버거',
    link: 'science/science-detail-9.html',
    category: '일반상식',
    author: '이호기',
    date: '08-21',
    views: 0,
    summary: '디버깅과 디버거',
  },
  {
    id: 8,
    title: '힘의 3요소',
    link: 'science/science-detail-8.html',
    category: '일반상식',
    author: '이호기',
    date: '08-20',
    views: 0,
    summary: '힘의 3요소의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 7,
    title: '쿼크 (Quark)',
    link: 'science/science-detail-7.html',
    category: '일반상식',
    author: '이호기',
    date: '08-19',
    views: 0,
    summary: '쿼크 (Quark)의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 6,
    title: '옴의 법칙',
    link: 'science/science-detail-6.html',
    category: '일반상식',
    author: '이호기',
    date: '08-18',
    views: 0,
    summary: '옴의 법칙의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 5,
    title: '열의 이동',
    link: 'science/science-detail-5.html',
    category: '일반상식',
    author: '이호기',
    date: '08-02',
    views: 0,
    summary: '열의 이동의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 4,
    title: '빛은 여러 가지 현상',
    link: 'science/science-detail-4.html',
    category: '일반상식',
    author: '이호기',
    date: '08-15',
    views: 0,
    summary: '빛은 여러 가지 현상의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 3,
    title: '상대성 이론',
    link: 'science/science-detail-3.html',
    category: '음펨바 효과 (Mpemba Effect)',
    author: '이호기',
    date: '08-14',
    views: 0,
    summary: '음펨바 효과 (Mpemba Effect)의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 2,
    title: "도플러 효과 (Doppler's effect)",
    link: 'science/science-detail-2.html',
    category: '일반상식',
    author: '이호기',
    date: '08-13',
    views: 0,
    summary:
      "도플러 효과 (Doppler's effect)의 개념, 특징, 비교 분석에 대한 설명",
  },
  {
    id: 1,
    title: '아르키메데스의 원리, 부력의 원리',
    link: 'science/science-detail-1.html',
    category: '일반상식',
    author: '이호기',
    date: '08-12',
    views: 0,
    summary:
      '아르키메데스의 원리, 부력의 원리의 개념, 특징, 비교 분석에 대한 설명',
  },
  // 여기에 추가 과학적 상식 데이터를 입력하세요
];
