// 경제상식 게시판 데이터
const economicsData = [
  {
    id: 62,
    title: 'GNI (Gross National Income)',
    link: 'economics/economy-detail-62.html',
    category: '경제 상식',
    author: '이호기',
    date: '09-07',
    views: 0,
    summary: 'GNI (Gross National Income)의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 61,
    title: '리세션 (Recession)',
    link: 'economics/economy-detail-61.html',
    category: '경제 상식',
    author: '이호기',
    date: '09-05',
    views: 0,
    summary: '리세션 (Recession)의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 60,
    title: '할로윈 효과(Halloween Effect)',
    link: 'economics/economy-detail-60.html',
    category: '경제 상식',
    author: '이호기',
    date: '09-03',
    views: 0,
    summary:
      '할로윈 효과(Halloween Effect)의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 59,
    title: "슈바베의 법칙(Schwabe's law)",
    link: 'economics/economy-detail-59.html',
    category: '경제 상식',
    author: '이호기',
    date: '08-28',
    views: 0,
    summary: "슈바베의 법칙(Schwabe's law)의 개념, 특징, 비교 분석에 대한 설명",
  },
  {
    id: 58,
    title: '레몬마켓',
    link: 'economics/economy-detail-58.html',
    category: '경제 상식',
    author: '이호기',
    date: '08-27',
    views: 0,
    summary: '레몬마켓의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 57,
    title: '기술적 분석 차트',
    link: 'economics/economy-detail-57.html',
    category: '경제 상식',
    author: '이호기',
    date: '08-26',
    views: 0,
    summary: '기술적 분석 차트의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 56,
    title: 'ISO 9001',
    link: 'economics/economy-detail-56.html',
    category: '경제 상식',
    author: '이호기',
    date: '08-25',
    views: 0,
    summary: 'ISO 9001의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 55,
    title: '산업재산권',
    link: 'economics/economy-detail-55.html',
    category: '경제 상식',
    author: '이호기',
    date: '08-23',
    views: 0,
    summary: '산업재산권의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 54,
    title: '공매도',
    link: 'economics/economy-detail-54.html',
    category: '경제 상식',
    author: '이호기',
    date: '08-22',
    views: 0,
    summary: '공매도의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 53,
    title: '파시',
    link: 'economics/economy-detail-53.html',
    category: '경제 상식',
    author: '이호기',
    date: '08-21',
    views: 0,
    summary: '파시의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 52,
    title: '브렌트 유와 WTI',
    link: 'economics/economy-detail-52.html',
    category: '경제 상식',
    author: '이호기',
    date: '08-20',
    views: 0,
    summary: '브렌트 유와 WTI의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 51,
    title: '클라크의 산업구조',
    link: 'economics/economy-detail-51.html',
    category: '경제 상식',
    author: '이호기',
    date: '08-19',
    views: 0,
    summary: '클라크의 산업구조의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 50,
    title: '헤지펀트와 사모펀트',
    link: 'economics/economy-detail-50.html',
    category: '경제 상식',
    author: '이호기',
    date: '08-18',
    views: 0,
    summary: '헤지펀트와 사모펀트의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 49,
    title: '건폐율과 용적율',
    link: 'economics/economy-detail-49.html',
    category: '경제 상식',
    author: '이호기',
    date: '08-16',
    views: 0,
    summary: '건폐율과 용적율의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 48,
    title: '세계 3대 신용평가기관',
    link: 'economics/economy-detail-48.html',
    category: '경제 상식',
    author: '이호기',
    date: '08-15',
    views: 0,
    summary: '세계 3대 신용평가기관의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 47,
    title: '방카슈랑스',
    link: 'economics/economy-detail-47.html',
    category: '경제 상식',
    author: '이호기',
    date: '08-14',
    views: 0,
    summary: '방카슈랑스의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 46,
    title: '모기지론 (Mortgage loan)',
    link: 'economics/economy-detail-46.html',
    category: '경제 상식',
    author: '이호기',
    date: '08-13',
    views: 0,
    summary: '모기지론 (Mortgage loan)의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 45,
    title: '미국통상법 301조(Section 301)',
    link: 'economics/economy-detail-45.html',
    category: '경제 상식',
    author: '이호기',
    date: '08-08',
    views: 0,
    summary:
      '미국통상법 301조(Section 301)의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 44,
    title: '패스포팅 (Passporting)',
    link: 'economics/economy-detail-44.html',
    category: '경제 상식',
    author: '이호기',
    date: '08-07',
    views: 0,
    summary: '패스포팅 (Passporting)의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 43,
    title: '로스차일드 가(Rothschild)',
    link: 'economics/economy-detail-43.html',
    category: '경제 상식',
    author: '이호기',
    date: '08-06',
    views: 0,
    summary: '로스차일드 가(Rothschild)의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 42,
    title: '그린라운드(Green Round)',
    link: 'economics/economy-detail-42.html',
    category: '경제 상식',
    author: '이호기',
    date: '08-05',
    views: 0,
    summary: '그린라운드(Green Round)의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 41,
    title: '블루라운드(Blue Round)',
    link: 'economics/economy-detail-41.html',
    category: '경제 상식',
    author: '이호기',
    date: '08-04',
    views: 0,
    summary: '블루라운드(Blue Round)의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 40,
    title: 'APEC(Asia-Pacific Economic Cooperation)',
    link: 'economics/economy-detail-40.html',
    category: '경제 상식',
    author: '이호기',
    date: '08-02',
    views: 0,
    summary:
      'APEC(Asia-Pacific Economic Cooperation)의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 39,
    title: '기축통화(Major Reserve Currency)',
    link: 'economics/economy-detail-39.html',
    category: '경제 상식',
    author: '이호기',
    date: '08-01',
    views: 0,
    summary:
      '기축통화(Major Reserve Currency)의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 38,
    title: '리쇼어링(Rebalancing)',
    link: 'economics/economy-detail-38.html',
    category: '경제 상식',
    author: '이호기',
    date: '07-31',
    views: 0,
    summary: '리쇼어링(Rebalancing)의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 37,
    title: '트릴레마(Trilemma)',
    link: 'economics/economy-detail-37.html',
    category: '경제 상식',
    author: '이호기',
    date: '07-30',
    views: 0,
    summary: '트릴레마(Trilemma)의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 36,
    title: 'BSI 지수(Business Survey Index)',
    link: 'economics/economy-detail-36.html',
    category: '경제 상식',
    author: '이호기',
    date: '07-29',
    views: 0,
    summary:
      'BSI 지수(Business Survey Index)의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 35,
    title: '통화 스왑(Currency Swap)',
    link: 'economics/economy-detail-35.html',
    category: '경제 상식',
    author: '이호기',
    date: '07-28',
    views: 0,
    summary: '통화 스왑(Currency Swap)의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 34,
    title: '네트워크 효과(Network Effect)',
    link: 'economics/economy-detail-34.html',
    category: '경제 상식',
    author: '이호기',
    date: '07-26',
    views: 0,
    summary:
      '네트워크 효과(Network Effect)의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 33,
    title: '기저효과(Base Effect)',
    link: 'economics/economy-detail-33.html',
    category: '경제 상식',
    author: '이호기',
    date: '07-25',
    views: 0,
    summary: '기저효과(Base Effect)의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 32,
    title: '구매력 평가(Purchasing Power Parity)',
    link: 'economics/economy-detail-32.html',
    category: '경제 상식',
    author: '이호기',
    date: '07-24',
    views: 0,
    summary:
      '구매력 평가(Purchasing Power Parity)의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 31,
    title: '인플레이션 타겟팅(Inflation Targeting)',
    link: 'economics/economy-detail-31.html',
    category: '경제 상식',
    author: '이호기',
    date: '07-23',
    views: 0,
    summary:
      '인플레이션 타겟팅(Inflation Targeting)의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 30,
    title: 'J-커브 효과(J-Curve Effect)',
    link: 'economics/economy-detail-30.html',
    category: '경제 상식',
    author: '이호기',
    date: '07-22',
    views: 0,
    summary: 'J-커브 효과(J-Curve Effect)의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 29,
    title: '슬라이딩 관세(Sliding Tariff)',
    link: 'economics/economy-detail-29.html',
    category: '경제 상식',
    author: '이호기',
    date: '07-21',
    views: 0,
    summary:
      '슬라이딩 관세(Sliding Tariff)의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 28,
    title: '폰지 사기(Ponzi Scheme)',
    link: 'economics/economy-detail-28.html',
    category: '경제 상식',
    author: '이호기',
    date: '07-19',
    views: 0,
    summary: '폰지 사기(Ponzi Scheme)의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 26,
    title: '콜(Call) / 콜금리(Call rate)',
    link: 'economics/economy-detail-26.html',
    category: '경제 상식',
    author: '이호기',
    date: '07-17',
    views: 0,
    summary: '콜(Call) / 콜금리(Call rate)의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 25,
    title: '지급준비율정책(Reserve Ratio Policy)',
    link: 'economics/economy-detail-25.html',
    category: '경제 상식',
    author: '이호기',
    date: '07-16',
    views: 0,
    summary: '지급준비율정책의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 24,
    title: '공개시장정책(Open Market Operation)',
    link: 'economics/economy-detail-24.html',
    category: '경제 상식',
    author: '이호기',
    date: '07-15',
    views: 0,
    summary: '공개시장정책의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 23,
    title: '개인워크아웃 (Individual workout)',
    link: 'economics/economy-detail-23.html',
    category: '경제 상식',
    author: '이호기',
    date: '07-14',
    views: 0,
    summary: '개인워크아웃의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 22,
    title: '디폴트(default, 채무불이행)',
    link: 'economics/economy-detail-22.html',
    category: '경제 상식',
    author: '이호기',
    date: '07-13',
    views: 0,
    summary: '디폴트의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 21,
    title: '경기동향지수(Economic Sentiment Index)',
    link: 'economics/economy-detail-21.html',
    category: '경제 상식',
    author: '이호기',
    date: '07-12',
    views: 0,
    summary: '경기동향지수의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 20,
    title: '잠재성장률(Potential growth rate)',
    link: 'economics/economy-detail-20.html',
    category: '경제 상식',
    author: '이호기',
    date: '07-11',
    views: 0,
    summary: '잠재성장률의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 19,
    title: '명목임금(Nominal wages) / 실질임금(Real wage)',
    link: 'economics/economy-detail-19.html',
    category: '경제 상식',
    author: '이호기',
    date: '07-10',
    views: 0,
    summary: '명목임금과 실질임금의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 18,
    title: '로렌츠곡선(Lorenz Curve)',
    link: 'economics/economy-detail-18.html',
    category: '경제 상식',
    author: '이호기',
    date: '07-09',
    views: 0,
    summary: '로렌츠곡선의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 17,
    title: '가처분소득(Disposable income)',
    link: 'economics/economy-detail-17.html',
    category: '경제 상식',
    author: '이호기',
    date: '07-08',
    views: 0,
    summary: '가처분소득의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 16,
    title: 'GNP와 NNP(GNP and NNP)',
    link: 'economics/economy-detail-16.html',
    category: '경제 상식',
    author: '이호기',
    date: '07-07',
    views: 0,
    summary: 'GNP와 NNP의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 15,
    title: '하이인컴트랩(High-income Trap)',
    link: 'economics/economy-detail-15.html',
    category: '경제 상식',
    author: '이호기',
    date: '07-06',
    views: 0,
    summary: '하이인컴트랩의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 14,
    title: '낙수효과(Trickle Down Effect)',
    link: 'economics/economy-detail-14.html',
    category: '경제 상식',
    author: '이호기',
    date: '07-05',
    views: 0,
    summary: '낙수효과의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 13,
    title: '카페라테 효과(caffe Latte Effect)',
    link: 'economics/economy-detail-13.html',
    category: '경제 상식',
    author: '이호기',
    date: '07-04',
    views: 0,
    summary: '카페라테 효과의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 12,
    title: '최소성의 원칙(The Principle of Least Cost)',
    link: 'economics/economy-detail-12.html',
    category: '경제 상식',
    author: '이호기',
    date: '07-03',
    views: 0,
    summary: '최소성의 원칙의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 11,
    title: '유동성 함정(Liquidity Trap)',
    link: 'economics/economy-detail-11.html',
    category: '경제 상식',
    author: '이호기',
    date: '07-02',
    views: 0,
    summary: '유돕성 함정의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 10,
    title: '피셔 효과(Fisher Effect)',
    link: 'economics/economy-detail-10.html',
    category: '경제 상식',
    author: '이호기',
    date: '07-01',
    views: 0,
    summary: '피셔 효과의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 9,
    title: "기펜의 역설(Giffen's Paradox)",
    link: 'economics/economy-detail-9.html',
    category: '경제 상식',
    author: '이호기',
    date: '06-29',
    views: 0,
    summary: '기펜의 역설의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 8,
    title: "그레이섬의 법칙(Gresham's Law)",
    link: 'economics/economy-detail-8.html',
    category: '경제 상식',
    author: '이호기',
    date: '06-28',
    views: 0,
    summary: '그레이섬의 법칙의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 7,
    title: '프로토콜 경제(Protocol Economy)',
    link: 'economics/economy-detail-7.html',
    category: '경제 상식',
    author: '이호기',
    date: '06-27',
    views: 0,
    summary: '프로토콜 경제의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 6,
    title: '드롭/래플(Drop/Raffle)',
    link: 'economics/economy-detail-6.html',
    category: '경제 상식',
    author: '이호기',
    date: '06-27',
    views: 0,
    summary: '드롭/래플의 개념, 특징, 비교 분석에 대한 설명',
  },
  {
    id: 5,
    title: '긱 경제(Gig Economy)',
    link: 'economics/economy-detail-5.html',
    category: '경제 상식',
    author: '이호기',
    date: '06-26',
    views: 0,
    summary: '긱 경제의 개념, 특징, 참여자에 대한 설명',
  },
  {
    id: 4,
    title: '출구전략(Exit Strategy)',
    link: 'economics/economy-detail-4.html',
    category: '경제 상식',
    author: '이호기',
    date: '06-26',
    views: 0,
    summary: '출구전략의 개념, 목적, 시기에 대한 설명',
  },
  {
    id: 3,
    title: '필립스 곡선(Phillips Curve)',
    link: 'economics/economy-detail-3.html',
    category: '경제 상식',
    author: '이호기',
    date: '06-24',
    views: 0,
    summary: '필립스 곡선의 개념, 원리, 의미에 대한 설명',
  },
  {
    id: 2,
    title: '갭 투자란 무엇일까?',
    link: 'economics/economy-detail-2.html',
    category: '경제 상식',
    author: '이호기',
    date: '06-24',
    views: 0,
    summary: '갭 투자의 의미와 예시',
  },
  {
    id: 1,
    title: '인플레이션이란 무엇일까?',
    link: 'economics/economy-detail-1.html',
    category: '경제 상식',
    author: '이호기',
    date: '06-24',
    views: 0,
    summary: '인플레이션의 개념, 원인, 영향 및 대응 방법에 대한 설명',
  },
  // 여기에 추가 경제상식 데이터를 입력하세요
];
